name: Jim's app

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install_deps
        run: |
          yarn install

      - name: build_app
        run: |
          yarn build

      - name: test_app
        run: |
          yarn test

  post_build:
    runs-on: ubuntu-latest
    container: node:16-alpine
    needs: build
    steps:
      - name: fake_step
        run: |
          echo "Added this fake step to test job-dependencies"
